### ISSUE TITLE
Filter by Custom Tags Question

### ISSUE THREAD

**Issue by AndriiHeonia** [angular/clutz#1005]
Hello,

First of all, thanks for the nice library.

I have a question about Clutz. We have a JavaScript API based on JSDoc and Closure Compiler, and we would like to use Clutz to generate d.ts file. The problem is that we don't want to generate TypeScript definitions for all methods, we want to generate them only for those methods which are published in our publicly available documentation. All the methods that go to public documentation are marked by our custom `@publish` tag. Is there any way to filter-out Clutz output? I see that there is `--skipEmitRegExp`, but I don't quite understand whether it can be used to solve this particular problem and if yes then what I should provide as a value for this parameter.

Thanks in advance for the response!

**Comment by rrdelaney** [comment]
Hi Andrii! Can you share a little more about your setup? Clutz is pretty much only meant to generate `d.ts` files for TypeScript code that is eventually using `goog.module` somewhere, and cannot be used to generate declarations for normal TypeScript code.

**Comment by AndriiHeonia** [comment]
Hi Ryan, our library is written in ES5 code, it's based on Google Closure Library and minified via Google Closure Compiler. I just want to generate `d.ts` file to make life easier for those users who include our library into their TypeScript projects.

Let's say I have those classes:

**./MyNamespace.js:**

```
/**
 * @namespace
 * @publish
 * @name MyNamespace
 */
goog.provide('MyNamespace');
```


**./MyUtilClass.js:**

```
goog.require('MyNamespace');
goog.provide('MyNamespace.MyUtilClass');

/**
 * @constructor
 */
MyNamespace.MyUtilClass = function() {};

/**
 * @param {string} msg
 */
MyNamespace.MyUtilClass.prototype.log = function(msg) {
  'use strict';
  console.log(msg);
};
```


**./MyClass.js**

```
goog.require('MyNamespace');
goog.require('MyNamespace.MyUtilClass');

goog.provide('MyNamespace.MyClass');

/**
 * @constructor
 * @publish
 */
MyNamespace.MyClass = function() {
  /**
   * @private
   * @type {MyNamespace.MyUtilClass}
   */
  this.util_ = new MyNamespace.MyUtilClass();
};

/**
 * @publish
 * @export
 * @param {number} x
 * @param {number} y
 * @return {number}
 */
MyNamespace.MyClass.prototype.add = function(x, y) {
  'use strict';
  this.util_.log('execute add');
  return x + y;
};

/**
 * @export
 * @param {number} x
 * @param {number} y
 * @return {number}
 */
MyNamespace.MyClass.prototype.subtract = function(x, y) {
  'use strict';
  this.util_.log('execute subtract');
  return x - y;
};
```

When I generate `d.ts` file via Clutz, I get totally valid type definitions:

<img width="790" alt="Screenshot 2020-05-08 at 14 15 29" src="https://user-images.githubusercontent.com/773648/81404731-7b3bce80-9136-11ea-93f5-6f7771432a9b.png">

The problem is that I don't want to expose methods that are not marked by our custom `@publish` tag. For example, I want to provide IntelliSense for `MyClass#add` method, but I don't want to provide it for `MyClass#subtract`.

Is it possible somehow to instruct Clutz to not include namespaces/classes/methods which are not marked by `@publish` tag into `d.ts` file? Or the only way to do that is to fork Clutz and change it?

Thanks for the help.

**Comment by rrdelaney** [comment]
I think you'll need to do additional processing to allow using that library in TypeScript. Clutz generates `d.ts` files for typings but cannot bridge the gap between the `goog.module` module system and TypeScript's. If you're pre-compiling the library for them using Closure Compiler and shipping it on npm Clutz may not work here either, the type definitions it emits are specifically for loading the library via Closure's module system 😞

Going back to the original topic, the `--skipEmitRegExp` is deprecated and shouldn't be used.

**Comment by AndriiHeonia** [comment]
Thanks for the answer, I'm closing the issue.
