### ISSUE TITLE
support goog.require output for empty namespaces

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#118]
In TS the following is an error
```
declare namespace foo {
	type Foo = number;
}

typeof foo;
```
clutz should not emit goog.require overloads for such namespace.

**Comment by mprobst** [comment]
`typeof foo` or `typeof foo.Foo`?

**Comment by rkirov** [comment]
foo is not a value when it is empty, so both fail at `foo`

**Comment by mprobst** [comment]
OK if it's not too hard to fix, long term we'll have to move to ES6 modules anyway.
