### ISSUE TITLE
Generate construct signatures for Closure's constructor-typed functions

### ISSUE THREAD

**Issue by mprobst** [angular/clutz#121]
Closure allows specifying a construct signature like this:
```js
/** @type {function(new:X, string, number)} */
var x;
```

We should translate this to a constructable interface:
```ts
var x: {new(a: string, b: number): X};
```

**Comment by rkirov** [comment]
didn't even know `f(new: ...)` existed. Any other magic `f(foo: type,...)` signatures known?
