### ISSUE TITLE
Prevent accidental structural typing

### ISSUE THREAD

**Issue by mprobst** [angular/clutz#131]
We could skip emitting private fields in `.d.ts` files. This allows better caching in build systems, but could also reduce the number of potentially problematic "overridden static field as wrong type" issues.

We should still emit a `private noStructuralTyping_: any;` field for every Closure `class`, to make sure classes don't accidentally get type compatible where they should not.

**Comment by rkirov** [comment]
We already skip private properties, for example:

https://github.com/angular/clutz/blob/f97f4b01219b50959cf1115ea4615a1c8b7cf2ae/src/test/java/com/google/javascript/clutz/fn_params.js#L36

and the output

https://github.com/angular/clutz/blob/f97f4b01219b50959cf1115ea4615a1c8b7cf2ae/src/test/java/com/google/javascript/clutz/fn_params.d.ts

noStructuralTyping for ones with private is good idea, so keeping the issue open.

**Comment by mprobst** [comment]
Odd, I thought I saw a case where we emit private static class fields.

In any case, will send a PR for the other issue.
