### ISSUE TITLE
non-private namespace var with a type of a private class errors

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#140]
example https://github.com/google/closure-library/blob/28d9db61f5dc639c010be74e4d61682121d2dbd7/closure/goog/events/actioneventwrapper.js#L49

we emit the var but not the class (thus type).

**Comment by mprobst** [comment]
Maybe we could fix the source? Nobody can use that symbol anyway.

**Comment by mprobst** [comment]
Actually people do. Funny thing that.

Maybe just emit as `any`?
