### ISSUE TITLE
null type is not emitted in `function(null=)`

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#141]
example https://github.com/google/closure-library/blob/28d9db61f5dc639c010be74e4d61682121d2dbd7/closure/goog/soy/soy.js#L116

**Comment by mprobst** [comment]
Wasn't this by design? In TypeScript, everything is always nullable, so stripping the `null` type is correct?

**Comment by mprobst** [comment]
Clarified offline, the problem is actually the `null` parameter, not the `null` member of the union type.
