### ISSUE TITLE
namespaces must be covariant with respect to classes

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#154]
```
class A {}
class B extends A {}

declare namespace A {
	var foo : {a:number};
}
declare namespace B {
	var foo : {};
}
```
is error in TS, but in closure A.foo and B.foo are not required to follow any type relation.

**Comment by rkirov** [comment]
Agreed to emit intersection type on the subtypes' namespace when 

```
class A {}
class B extends A {}

declare namespace A {
	var foo: {a: string};
}

declare namespace B {
	var foo: {} & {a:string}
}
```

**Comment by mprobst** [comment]
Maybe worth noting: that's better than emitting union types on the parent,
because the resulting type is more useful (i.e. can still use properties
off of the parent type, only the child type get's a bit cluttered). It also
turns out to be easier to implement...
