### ISSUE TITLE
Type name issue converting polymer externs

### ISSUE THREAD

**Issue by rictic** [angular/clutz#160]
[Source file](https://github.com/PolymerLabs/polymer-externs/blob/master/polymer.externs.js)

Specifically, this declaration:

```javascript
/**
 * Returns a Polymer-friendly API for manipulating DOM of a specified node or
 * an event API for a specified event..
 *
 * @param {?Node|?Event} nodeOrEvent
 * @return {!PolymerDomApi|!PolymerEventApi}
 */
Polymer.dom = function(nodeOrEvent) {};
```

Gets converted to:

```typescript
declare namespace ಠ_ಠ.clutz_internal.Polymer {
  // ...
  function dom (nodeOrEvent : Node | Event ) : omApi | ventApi ;  
}
```

Note that `!PolymerDomApi|!PolymerEventApi` becomes `omApi | ventApi`.

**Comment by mprobst** [comment]
I cannot reproduce this wit the latest Clutz - though we do have other issues. I'll file separately for those.
