### ISSUE TITLE
TypeScript is missing some platform externs (or might use different names)

### ISSUE THREAD

**Issue by mprobst** [angular/clutz#170]
* [ ] IDBDatabaseException
* [ ] Image

**Comment by mprobst** [comment]
Turns out that `IDBDatabaseException` was [removed from the spec](https://developer.mozilla.org/de/docs/Web/API/IDBDatabaseException), and `Image` is provided in a later TypeScript version, so we just have to upgrade.

**Comment by rkirov** [comment]
fixed with https://github.com/angular/clutz/commit/4606e52931d7322fb70644e06b72548258aaa490
