### ISSUE TITLE
Possibly handle untyped object structures

### ISSUE THREAD

**Issue by mprobst** [angular/clutz#182]
Clutz currently doesn't emit a usable type for code that `provide`s something, but then doesn't add a `@type` (or `@const`). This leads to a `provide` without a `symbol`, which we emit as an empty object, which is not usable.

An alternative fix would be changing the Closure code to actually produce a proper type.

**Comment by rkirov** [comment]
Fixed as seen in this unit test:

closure:
https://github.com/angular/clutz/blob/master/src/test/java/com/google/javascript/clutz/untyped_provide.js#L7
typescript:
https://github.com/angular/clutz/blob/master/src/test/java/com/google/javascript/clutz/untyped_provide.d.ts#L2

AFAIKT, closure does not infer the types, so the best we can do is emit 'any'.
