### ISSUE TITLE
Fix static inheritance mismatches by separating static and instance inheritance chain

### ISSUE THREAD

**Issue by mprobst** [angular/clutz#184]
In Closure's type system, there are no classes, but rather just constructor functions. In contrast to TypeScript classes, constructor functions do not inherit static properties from their parents. Clutz has to generate actual classes and cannot use the `interface X {}; var X: { new(): X; ... statics from x ... }` trick, because Closure exposes nested classes within constructor functions. The nested classes must be represented in TS namespaces, as they are accessible as properties on their containing class, and the `var`s in above trick collide with namespace declarations.

A reasonable fix for this situation is separating the static hierarchy and the instance hierarchy, with only the instance hierarchy inheriting, and the static hierarchy extending the non-static counterparts. This matches the actual Closure inheritance semantics. The exception are ES6 classes that currently have no correct representation in Closure's type system, but are also very rarely used.

E.g. for the three classes inheriting in chain: `Child -> Parent -> GrandParent`, the effective inheritance chain would be (with `_I` representing the instance fields of the respective class, and `A == Ancestor == GrandParent`):

```
+-----+    +---+
| A_I <----+ A |
+--^--+    +---+
   |
+--+--+    +---+
| P_I <----+ P |
+--^--+    +---+
   |
+--+--+    +---+
| C_I <----+ C |
+-----+    +---+
```

And the corresponding TS declarations:

```ts
declare namespace x {
  class GrandParent extends GrandParent_Instance {
    static gpStatic: string;
  }
  class GrandParent_Instance {
    gpField: string;
  }
  class Parent extends Parent_Instance {
    static parentStatic: string;
  }
  class Parent_Instance extends GrandParent_Instance {
    parentField: string;
  }
  class Child extends Child_Instance {
    static childStatic: string;
    constructor(x: number);  // ctors are part of the static aspect of a class
  }
  class Child_Instance extends Parent_Instance {
    childField: string;
  }
}

declare namespace x.GrandParent {
  class Z {}  
}

declare namespace x.Parent {
  class Z {}  // Look, no collision!
}

var p = new x.Parent();
```

**Comment by mprobst** [comment]
@rkirov please double check if I correctly captured our thoughts.

**Comment by rkirov** [comment]
your ascii picture arrows are wrong `A_I -> A`, otherwise fine.

**Comment by rkirov** [comment]
lgtm
