### ISSUE TITLE
Issue with nullable types as return types of overriden methods.

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#197]
The following is valid Closure code:

```javascript
/**
 * @constructor
 */
A = function() {};

/**
 * @param {string} a
 * @return {A}
 */
A.prototype.foo = function(a) {};

/**
 * @constructor
 * @extends {A}
 */
B = function() {};

/**
 * @param {string} a
 * @return {null}
 */
B.prototype.foo = function(a) {return null;};
```

Because Object is nullable, the null type is subtype of A. Clutz outputs 

```typescript
class A {
  foo(a: string): A;
}

class B extends A {
  foo(a: string): void;
}
```

Unfortunately that is an error in TS because the void type is only subtype of any (per spec). The same issue happens with `undefined` instead of `null`.

Two possible solutions come to mind:
- output `foo(a: string): any;` in B, when this issue is detected (easier to detect from B than from A). We are losing some type info on B.
- output `foo(a: string): A | void;` (needs a global pass to find that B has type void). It would make the api a lot harder to work with on the TS side.

**Comment by mprobst** [comment]
As commented elsewhere, have you considered option three:
* output `foo(a: string): void&A;` in B when this issue is detected. Makes for an odd signature, but works.

**Comment by rkirov** [comment]
Clutz now outputs null types, thus matching closure. In the particular case outlines 'null' stays as 'null', and there no 'void' weirdness involved.
