### ISSUE TITLE
handle methods vs function fields

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#199]
Closure makes no distinction between a class method and a field that happens to be of function type. Thus one can extend the other.
```javascript
/** @constructor */
var A = function() {
  /** @type{function(number)} */
  this.foo = function(a) {};

}

/**
 * @constructor
 * @extends {A}
 */
var B = function() {

}
/**
 * @override
 * @param {number} a
 */
B.prototype.foo = function(a) {};
```

However, that is illegal in TS. The current output is:
```typescript
declare module M {
	class A {
		foo: ((a: string) => void);
	}

	class B extends A {
		foo(a:string): void;
	}
}
```
which has the ```Class 'A' defines instance member property 'foo', but extended class 'B' defines it as instance member function``` error.

Such cases are very rare, so I say we just do an extra check up the inheritance chain and reconcile into the type that the base class has (field or method). Unless I am mistaken this should not affect the user of the foo API.

**Comment by mprobst** [comment]
I just fixed another issue like that in some Closure code. I think Closure
is not quite correct here - the intent of the code with the property
definition is that this is a readable & writable property, but defining a
method means your code expects to be read-only. So fixing the code is an
option, but OTOH if we have many such cases it might be more efficient to
handle the case.

Rado Kirov <notifications@github.com> schrieb am Di., 22. Dez. 2015 um
01:42 Uhr:

**Comment by rkirov** [comment]
Here is the actual usage site -
https://github.com/google/closure-library/blob/753975da0979b0bb3b5c9326d93e2dd499a92e76/closure/goog/ui/ac/renderer.js#L1106

The intent is to fully support overriding to null value, something that cannot be expressed with @param annotation.

**Comment by mprobst** [comment]
@rkirov is `null` really the issue there? I'd expect the problem to be that one class defines `render` as an assignable field, and the other defines it as a method, which is not assignable - right?

**Comment by mprobst** [comment]
Occurs in other places, too.

**Comment by rkirov** [comment]
I have a lot better understanding of this issue now, see the test cases in the PR.

Closure treats everything as a prop (closer to JS view of the world). We use type.isFunction() to emit function vs prop and in the example above type {function | null | undefined } returns false, thus we emit as  field but later overwrite by a function.
