### ISSUE TITLE
inferred object types should emit type literals 

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#202]
The following closure code:

``` javascript
/**
 * @const
 */
var constObj = {};

/**
 * @type {number}
 */
var constObj.num;
```

relies on type inference to deduce the type of `constObj` to be `{num : number}` (or at least that's how it appears, because `constObj.bar` fails to typecheck.)

Currently we emit `constObj : Object` which is not correct. Closure has the right information to output correct type literal type `{num : number}`.

**Comment by dpurp** [comment]
If I remember correctly, Closure treats constObj as a namespace rather than an 'object'. 

That is, in Closure, this:
```
/**
 * @const
 */
var constObj = {};
```

Is different from this:
```
/**
 * @const {!Object}
 */
var constObj = {};
```

**Comment by rkirov** [comment]
We must have fixed this at some point in the last 2 years, because this is no longer an issue.
