### ISSUE TITLE
Should translate `Function` to `Function`

### ISSUE THREAD

**Issue by mprobst** [angular/clutz#263]
Clutz currently translates `Function` into an `(...args: any[]) => any` type. However that does not match `Function`, which in Closure is a supertype and subtype of anything that's callable (including e.g. classes).

TypeScript does actually have a `Function` type that seems more appropriate.

**Comment by rkirov** [comment]
fixed at head with https://github.com/angular/clutz/commit/88de5f0f3103828288cba0b8f0296281690372bc
