### ISSUE TITLE
`goog.module` broken for simple const fields

### ISSUE THREAD

**Issue by mprobst** [angular/clutz#265]
```js
goog.module('foo.Bar');
/** @const */
exports.FOO = 'bar';
```

```ts
declare module foo {
  var Bar: any;
}
```

**Comment by mprobst** [comment]
I think that's a consequence of the recent goog.module change.

**Comment by mprobst** [comment]
@rehmsen

**Comment by rkirov** [comment]
yes, clutz only sees modules which have `goog.module.declareLegacyNamespace()`

**Comment by rehmsen** [comment]
Thanks for confirming. Is this something you are planning to fix? Is there any timeline for this? I suppose we can work around this by always declaring legacy namespace, I am not sure what downsides that would have - I guess there is a reason this is now legacy...

**Comment by rkirov** [comment]
Fixed with https://github.com/angular/clutz/commit/ed1613d579725cf660e6e0e594ece48aed2c7f75
