### ISSUE TITLE
Duplicate declaration of static methods.

### ISSUE THREAD

**Issue by jDramaix** [angular/clutz#268]
Static method are declared two times. On the class and on a namespace having the same fully qualified name of the class.

```
declare namespace ಠ_ಠ.clutz {
  class Date extends Date_Instance {
    static now ( ) : number ;
    static parse (date : any ) : number ;
    // ...
  }

declare namespace ಠ_ಠ.clutz.Date {
  function now ( ) : number ;
}
declare namespace ಠ_ಠ.clutz.Date {
  function parse (date : any ) : number ;
}
```

**Comment by rkirov** [comment]
I tried to reproduce this https://github.com/angular/clutz/tree/double_statics, but I only see a single static. Can you spot whats wrong with my repro case https://github.com/angular/clutz/commit/25e7b12caff95386896731e25028fbe9087f3115
