### ISSUE TITLE
move class Foo, Foo_instance pair to interfaces

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#272]
Currently, we emit a `Foo` (static side) and `Foo_Instance` (instance side) classes for each closure class Foo.

This pattern has an issue that if `Bar extends Foo` in closure the corresponding classes in TS are no longer subtypes. An alternative would be:
 
```typescript
interface Date_Static {
    new(args): Date;
    // instance methods.
    now(): number ;
}

interface Date {
    // static methods.
    getDate(): number ;
}

declare var Date: Date_Static;
```

This is preferable, my only concern being that classes and namespace can share a symbol, but var and namespaces can't.

**Comment by jDramaix** [comment]
one another issue that would be fixed if Clutz emit interface instead of class:
For the time being, when a class extends an interface, it doesn't redeclare the method of the interface and so produce invalid TS code.

Ex:

```javascript
/**
 * @record
 * @template VALUE2
 */
function IArrayLike() {}

/** @type {number} */
IArrayLike.prototype.length;

/**
 * @constructor
 * @implements {IArrayLike<T>}
 * @param {...*} var_args
 * @return {!Array<?>}
 * @nosideeffects
 * @template T
 */
function Array(var_args) {}
```

is converted to 

```typescript
declare namespace ಠ_ಠ.clutz {
  class Array < T > extends Array_Instance < T > {
  }
  class Array_Instance < T > implements IArrayLike < T > {
    private noStructuralTyping_: any;
    constructor ( ...var_args : any [] ) ;
    [key: string]: any;
}
declare namespace ಠ_ಠ.clutz {
  interface IArrayLike < VALUE2 > extends IObject < number , VALUE2 > {
    length : number ;
  }
}
```

And typescript compiler complaints on the Array_Instance class: "Property length from IArrayLike interface is not implemented"

**Comment by rkirov** [comment]
I prototyped this solution, and decided against checking it in. Here is the reasoning:

- it is not true that the subtyping is broken. This one is subtle, say in closure we have `Bar extends Foo` for classes, we will translate this to `Bar extends Bar_Instance`, `Foo extends Foo_Instance` and `Bar_Instance extends Foo_Instance`. Now it seems there there is no "extends" path from `Foo` to `Bar`. However, TS type system is structural and `Bar` and `Foo` local definitions contain only static methods, thus their types are equivalent to `Bar_Instance` and `Foo_Instance`, and indeed the subtyping relation `Bar` is a subtype of `Foo` holds in TypeScript.

- if we move to interfaces we cannot do the `private _noStructuralTyping` key trick, thus openning the door for possibly people using object literals when Closure types are required. That will result in Closure errors down the pipeline.
