### ISSUE TITLE
Add nullability support

### ISSUE THREAD

**Issue by jDramaix** [angular/clutz#273]
It seems that typescript is adding nullable and non-nullable type: https://github.com/Microsoft/TypeScript/pull/7140

As Closure has already this notion of nullability, it would be nice that clutz convert it.

**Comment by rkirov** [comment]
Yes, that is on top of my list. They mention "Pragma to indicate declaration file has been updated to use null- and undefined-aware types" on the github issue, but I never saw that land.

**Comment by rkirov** [comment]
fixed by https://github.com/angular/clutz/commit/ad0db17cdba276b0f187216dd8a5bc232e938de5
