### ISSUE TITLE
No types generated for proto nested enums 

### ISSUE THREAD

**Issue by rehmsen** [angular/clutz#275]
For a proto file with a nested enum

    message Foo {
      enum Bar {
         BAZ = 0;
      }

      Bar bar = 1;
    }

Clutz skips the nested enum and generates

    interface Foo {
      bar : ಠ_ಠ.clutz.Foo.Bar ;
    }

But no type for Bar. The Typescript compiler then complains:

> Module 'ಠ_ಠ.clutz.' has no exported member 'Foo'.

In my own code I can move the enum out of the message, but this is also happening for protos that are pulled in by my dependencies, where this is more tricky. 
Not sure if this is only broken for enums or for any nested message.

Any workaround? Any timeline for getting this fixed?

**Comment by rkirov** [comment]
I think there is something more at play here. We do support inner enums, for example -https://github.com/angular/clutz/blob/master/src/test/java/com/google/javascript/clutz/fn_inner_enum.js

I would need to see some of the closure code generated from the protocol buffer definition to debug further, since there are multiple competing javascript pb generators.

**Comment by rehmsen** [comment]
Here is some more context.
This is our dependency structure: 
ts_library.deps -> js_library.srcs -> gen_js_enums

gen_js_enums is a macro for a genrule extracting JS code for enums from proto files. Its output looks like this:

    /**
     * Generated from enum Foo.Bar in:
     * foo.proto
     *
     * @export @enum {my.package.Foo.Bar<string>}
     */
    enums.my.package.Foo.Bar = {
      'BAZ': /** @type {json.my.package.Foo.Bar<string>} */('BAZ'),
    };

Clutz turns that into:

    declare namespace ಠ_ಠ.clutz.enums.my.package.Foo {
      /**
       * Generated from enum Foo.Bar in:
       * foo.proto
       */
      type Bar = ಠ_ಠ.clutz.json.my.package.Foo.Bar ;
      var Bar : {
        BAZ : Bar ,
      };
    }
    declare namespace ಠ_ಠ.clutz.goog {
      function require(name: 'enums.my.package.Foo.Bar'): typeof ಠ_ಠ.clutz.enums.my.package.Foo.Bar;
    }
    declare module 'goog:enums.my.package.Foo.Bar' {
      import alias = ಠ_ಠ.clutz.enums.my.package.Foo.Bar;
      export default alias;
    }

And Typescript then complains that about `type Bar = ಠ_ಠ.clutz.json.my.package.Foo.Bar ;`

> Module 'ಠ_ಠ.clutz.json.my.package' has no exported member 'Foo'.

Notice that the error is about a missing **json**.my.package.Foo, which is actually a defined in the externs, so my first error was not adding the gen_proto_externs for the same proto into the externs_list of the ts_library. I fixed that now, and indeed I can now find the following in my Clutz-generated d.ts file:

    declare namespace ಠ_ಠ.clutz.json.my.package {
      /**
       * Generated from message Foo in:
       * foo.proto
       */
      interface Foo {
        bar : ಠ_ಠ.clutz.json.my.package.Foo.Bar ;
      }
    }

But I still get the same error. I noticed that ಠ_ಠ.clutz.json.my.package.Foo is declared later in the Clutz-generated d.ts than ಠ_ಠ.clutz.enums.my.package.Foo - could that be the problem? Any way I can force the order? Or is there something else I am missing?

**Comment by rehmsen** [comment]
Looking at this some more, I think the problem might just be that gen_js_externs declares the type **enums**.my.package.Foo.Bar, but then gen_js_enums references the type json.my.package.Foo.Bar. That would indeed not work. So I guess the question is: How did this ever work with JSCompiler? 

If I am not mistaken, this is no Clutz issue after all, but rather an issue with gen_js_externs/enums and JSCompiler. Closing this for now, I will reopen if necessary.

**Comment by rehmsen** [comment]
I think I understand now why this does work in JSCompiler. 
My earlier comment did not have the JSCompiler code the gen_js_externs rule produces:

    /**
     * Generated from message Foo in:
     * foo.proto
     *
     * @interface
     */
    json.my.package.Foo = function() {};

    /**
     * @type {!json.my.package.Foo.Bar|
     *        undefined}
     */
    json.my.package.Foo.prototype.bar;

    /**
     * Generated from enum Foo.Bar in:
     * foo.proto
     *
     * @enum {string}
     */
    json.my.package.Foo.Bar = {
      'BAZ': 'BAZ',
    };

Notice how the last part, the declaration of the type json.my.package.Foo.Bar does not make it into the Clutz output:

    declare namespace ಠ_ಠ.clutz.json.my.package {
      /**
       * Generated from message Foo in:
       * foo.proto
       */
      interface Foo {
        bar : ಠ_ಠ.clutz.json.my.package.Foo.Bar ;
      }
    }

And then that type is aliased with `type Bar = ಠ_ಠ.clutz.json.my.package.Foo.Bar ;`, which does not work because the type is not declared. 
So the question is, why does Clutz not generate a type like 

    namespace ಠ_ಠ.clutz.json.my.package.Foo {
        enum Bar {
          BAZ
        }
    }

**Comment by rkirov** [comment]
Thanks, Ole!

I got a reproduction from this, working on a fix.

**Comment by rehmsen** [comment]
This indeed solved it in many cases, but it seems to still be missing recursively nested protos. Basically, 
I have another proto that is nested Foo > Bar > Baz
My externs generator outputs stuff like

    /** @interface */
    package.Foo = function() {};
    /** @interface */
    package.Foo.Bar = function() {};
    /** @interface */
    package.Foo.Bar.Baz = function() {};

And with your fix, Clutz outputs

    declare namespace package {
       interface Foo { ... }
    }
    declare namespace package.Foo {
      interface Bar { ... }
    }

But not 

    declare namespace package.Foo.Bar {
      interface Baz { ... }
    }
