### ISSUE TITLE
Dictionary keys starting with digits do not work

### ISSUE THREAD

**Issue by rehmsen** [angular/clutz#276]
Our D3 externs contain something like this:

    'symbolTypes': {
       '0': {},
       '1': {},
       '2': {},
       '3': {},
       '4': {},
       '5': {}
     },

Clutz tries to make that:

    declare namespace ಠ_ಠ.clutz.d3.svg.symbolTypes {
      var 0 : Object ;
    }
    declare namespace ಠ_ಠ.clutz.d3.svg.symbolTypes {
      var 1 : Object ;
    }
    declare namespace ಠ_ಠ.clutz.d3.svg.symbolTypes {
      var 2 : Object ;
    }
    declare namespace ಠ_ಠ.clutz.d3.svg.symbolTypes {
      var 3 : Object ;
    }
    declare namespace ಠ_ಠ.clutz.d3.svg.symbolTypes {
      var 4 : Object ;
    }
    declare namespace ಠ_ಠ.clutz.d3.svg.symbolTypes {
      var 5 : Object ;
    }

But that does not work because identifiers must not start with digits.

**Comment by rkirov** [comment]
I thought I fixed this issue in - https://github.com/angular/clutz/commit/613701db83a14669bdda271b663a4cc559e8d8da
but I see I missed a case. Should be a oneline change, stay tuned.
