### ISSUE TITLE
Reference to typedefs of the Global scope are emitted under window global scope

### ISSUE THREAD

**Issue by jDramaix** [angular/clutz#292]
If a typedefs is defined on the global scope, clutz emits it on `window` namespace. I guess this information come from Closure, but it would be nice if clutz could emit them on the global namespace.

``` javascript
/**
 * @typedef {{contentType: string, robustness: string}}
 */
var MediaKeySystemMediaCapability;
```

is converted to:

```
declare namespace ಠ_ಠ.clutz.window {
  type MediaKeySystemMediaCapability = { contentType : string , robustness : string } ;
}
```

It would be better to have `MediaKeySystemMediaCapability` defined on `ಠ_ಠ.clutz`

**Comment by rkirov** [comment]
This has not been an issue for us, because by design clutz does not expect users to consume externs through clutz.
