### ISSUE TITLE
Allow only emitting types reachable from certain files

### ISSUE THREAD

**Issue by mprobst** [angular/clutz#297]
E.g. have fileA.js, fileB.js as "roots", but then generate type definitions for symbols defined in these files and all symbols transitively reachable from the files. This should not produce `goog:...` module declarations for the transitively reachable types.

The reasoning is that this could substantially cut the generated .d.ts file size, and implements a form of strict dependency checking – there will not be a `goog:` module for types not immediately included as a root, so users cannot use the type without importing it explicitly.

**Comment by rkirov** [comment]
This is impossible with incremental clutz. We do not have any ability to make decisions beyond the one file clutz is translating at the time.
