### ISSUE TITLE
Classes cannot be extended with namespaces in externs files

### ISSUE THREAD

**Issue by lambertjamesd** [angular/clutz#299]
Given the following in an externs file
```javascript
/**
 * @constructor
 */
function Foo() {}

Foo.bar = {};

Foo.bar.fn = function() {};
```
The output is
```typescript
declare namespace ಠ_ಠ.clutz {
  class Foo extends Foo_Instance {
    static bar : Object ;
  }
  class Foo_Instance {
    private noStructuralTyping_: any;
  }
}
declare namespace ಠ_ಠ.clutz.Foo.bar {
  function fn ( ) : any ;
}
```
Foo gets a static member, bar, and then it is used as a namespace afterward. The static member should not be there.

**Comment by rkirov** [comment]
ouch! In non-externs we are guided by `goog.provides` in deciding what becomes a namespace in TS and what doesn't. In externs there are no goog.provides, so we are left to heuristics (see `isLikelyNamespace`).

Is the bug there when one writes:
```
/** @const */
Foo.bar = {};
```
This is the pattern most commonly used in Google to denote a "namespace" in closure externs.

**Comment by lambertjamesd** [comment]
Adding `@const` seems to fix it. Thanks.

**Comment by lambertjamesd** [comment]
Adding `@const` to the namespace seems like the right way to handle this. I think I'll close this since there really isn't a bug.
