### ISSUE TITLE
Generate optional properties from `<type>|undefined`

### ISSUE THREAD

**Issue by gmoothart** [angular/clutz#306]
In our closure typedefs, we use `type|undefined` to represent an object property that is optional.
An example is the "parent" property here:

```
goog.provide('organization.OrganizationData');

/** @record */
organization.OrganizationData = function() {};

/** @export {string} */
organization.OrganizationData.prototype.key;

/** @export {string} */
organization.OrganizationData.prototype.name;

/** @export {!organization.OrganizationData|undefined} */
organization.OrganizationData.prototype.parent;
```

When clutz runs over this file, it just copies over the "| undefined" and produces:
```
  interface OrganizationData {
    key : string ;
    name : string ;
    parent : ಠ_ಠ.clutz.organization.OrganizationData | undefined ;
  }
```
When I create a variable of type OrganizationData, typescript insists that I include the optional properties as well. I think it would be better for clutz to special-case this and output optional properties - like "parent?" - instead.

**Comment by polybuildr** [comment]
+1 This is also necessary when trying to generate a TS declarations file from protos: running it through an internal Google tool generates closure annotations which then get handled the same way as the case above. Instead, it should be possible to not initialize `optional` proto fields, for which Clutz would need to support optional properties in the interface.
