### ISSUE TITLE
Handle interfaces, structs and enumerations.

### ISSUE THREAD

**Issue by obsc** [angular/clutz#315]
Add support for the following annotations:
- [x] `@interface`
- [x] `@struct`
- [ ]  `@enum`

**Comment by ewinslow** [comment]
@enum is going to be tough because often the actual value of the enum is a non-number, which is different from TypeScript where they're always numbers IIRC. What are the downsides to just leaving it alone?

**Comment by dpurp** [comment]
@interface supported added in #361 
@typedef supported added in #362

**Comment by mprobst** [comment]
@ewinslow yeah, I think our recommended pattern for enums that have complex values is to just use an object literal and depend on the resolved type. That doesn't give you enum semantics (i.e. must be one of a limited set of items), but it's mostly there:

```ts
const FooOptions = {
  BAR: {a: 1, b: 'x'},
  BAZ: {a: 2, b: 'y'},
  ...
};
```

@rkirov has been thinking about this a bit.

**Comment by mprobst** [comment]
In that light, the remaining work here is to check that gents' output for `@enum` is reasonable.

**Comment by rkirov** [comment]
With TS 2.4 and string enums, I think number and strings cover enough cases to justify proper emit of TS enums. For the rest the current emit is not too terrible (original object literal), but we should at least have tests for it to not inadvertently change it.

**Comment by rkirov** [comment]
Enum support was added in https://github.com/angular/clutz/commit/66834dfe8e27a60bdebcd5c9a1084184ecd0b92b#diff-e51157c4067a1460f5df7ae32287fe6d
