### ISSUE TITLE
[gents] Handle goog.base

### ISSUE THREAD

**Issue by ochafik** [angular/clutz#322]
Example:

``` javascript
goog.provide('Child');
goog.require('Parent');

/**
 * @constructor @extends {Parent}
 * @param {number} x.
 */
Child = function(x) {
  goog.base(this, x);
};
goog.inherits(Child, Parent);

/** @override */
Child.prototype.foo = function(y) {
  goog.base(this, 'foo', y);
};
```

Should generate something like:

``` javascript
class Child extends Parent {
  constructor(x: number) {
    super(x);
  }
  foo(y) {
    super.foo(y);
  }
}
```

It might be that [goog.base is being deprecated](https://github.com/google/closure-library/wiki/How-to-migrate-from-goog.base) (?), but it's still quite widespread in Closure codebases.

**Comment by ochafik** [comment]
Also, the `goog.inherits` call should be ditched :-)

**Comment by rkirov** [comment]
Migrating to ES6 classes is complicated by some runtime reasons, so we are going to focus only on ES6 classes input, and expect input to be premigrated to ES6.
