### ISSUE TITLE
[gents] Non-idiomatic function export style

### ISSUE THREAD

**Issue by ochafik** [angular/clutz#325]
```js
goog.provide('foo.main');
foo.main = function() {};
```
Could be converted to idiomatic:
```js
export function main() {};
```

Instead of:
```js
export const main = function() {};
```

**Comment by obsc** [comment]
fd10f967aa924d255b8b6b864e12f4ea259a636c should have already resolved this.
The version of gents you used was probably not synced up to the most recent commit.

reopen if I'm mistaken.

**Comment by ochafik** [comment]
Thanks, I was indeed using an older version!
