### ISSUE TITLE
[gents] Non-namespaced top-level function not exported?

### ISSUE THREAD

**Issue by ochafik** [angular/clutz#326]
Not sure if it's valid Closure, but the output seems wrong here:

``` js
goog.provide('foo');
function foo() {}
```

Gives:

``` js
export{};
function foo() {
}
```

I would have expected:

``` js
export function foo() {}
```

(note that using the `foo = function() {}` syntax works)

**Comment by mprobst** [comment]
I guess that's sort of valid Closure syntax, but very surprising, isn't it? I've never seen that pattern, so this might not be a priority?

**Comment by ochafik** [comment]
Def. not a priority, but still thought I'd report it :-)
