### ISSUE TITLE
handle closures' type transformation expressions

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#331]
Closure supports type macros, for example for typing out Promise:

```js
/**
 * @constructor
 * @template T
 */
angular.$q.Promise = function() {};

/**
 * Apply Type Transformation Language to allow more accurate templated type
 * definition.
 * This is copied from <code>goog.Thenable.prototype.then</code>, with the only
 * difference being the raw type as angular.$q.Promise instead of goog.Promise.
 *
 * @param {?(function(this:THIS, T): VALUE)=} opt_onFulfilled
 * @param {?(function(?): ?)=} opt_onRejected
 * @param {?(function(?): ?)=} opt_notifyCallback
 * @return {RESULT}
 * @template THIS
 * @template VALUE
 * @template RESULT := type('angular.$q.Promise',
 *     cond(isUnknown(VALUE), unknown(),
 *       mapunion(VALUE, (V) =>
 *         cond(isTemplatized(V) && sub(rawTypeOf(V), 'IThenable'),
 *           templateTypeOf(V, 0),
 *           cond(sub(V, 'angular.$q.Promise'),
 *              unknown(),
 *              V)))))
 *  =:
 */
angular.$q.Promise.prototype.then =
    function(opt_onFulfilled, opt_onRejected, opt_notifyCallback) {};
```

Currently, clutz doesn't choke on this, but produces a not very usable type:

```ts
    then < THIS , VALUE , RESULT > (opt_onFulfilled ? : ( (a : T ) => VALUE ) | null , opt_onRejected ? : ( (a : any ) => any ) | null , opt_notifyCallback ? : ( (a : any ) => any ) | null ) : RESULT ;
  }
```
Since the dependency on `VALUE` and `RESULT` is lost, it is always the empty object type `{}`. Thus a promise of this type is unusable after `promise.then(x => x)`.

This feature is not heavily used, so even a first order approximation say using `VALUE` instead of  `RESULT` will make the generated promise types a lot more useful. It will be missing the Promise unwrapping feature, but that is not as common simply returning the result type.

**Comment by mprobst** [comment]
I think you could even just hard code the special case of promise itself.
Though we'll need to make sure that whatever we also works for ipromise etc.

Rado Kirov <notifications@github.com> schrieb am Mi., 24. Aug. 2016, 01:40:

**Comment by rkirov** [comment]
already did, take a look at https://reviews.angular.io/D244
