### ISSUE TITLE
Incremental file conversion in gents

### ISSUE THREAD

**Issue by obsc** [angular/clutz#333]
Allow gents to be run incrementally where you only convert a few files at a time.
In each progressive pass, it should update the imports in the previous files.

**Comment by gmoothart** [comment]
The main problem here is with existing closure files that reference the newly converted files. The imports for that file in existing closure code has to change from `goog.require('foo.a')` to `goog.require('google3...foo.a')`

gents could output a mapping from old to new namespace, to be used by sed to fixup the existing code:
`foo.a -> google3...foo.a`
