### ISSUE TITLE
gents outputs mis-alligned jsdoc comments

### ISSUE THREAD

**Issue by gmoothart** [angular/clutz#376]
example:
https://github.com/angular/clutz/blob/a39822fd3d74c8254ca0e943b5555746b7ac7627/src/test/java/com/google/javascript/gents/singleTests/static_methods.ts#L9

Seems like it would be best for clang to handle this.

**Comment by dpurp** [comment]
I suspect this is from an over-eager regex trimming in `CommentLinkingPass`

**Comment by dpurp** [comment]
Fixed with update to clang-format in https://github.com/angular/clutz/commit/7db988fa59a068cf2eb6da121aa461dec99b4b5e
