### ISSUE TITLE
Emit const instead of let when the variable is not reassigned

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#379]
It would require a look through the current lexical scope to find any reassignments. It has tricky edge cases with closures introducing new scopes and possible shadowing of variable with the same name.

This is a google internal user feature request.

**Comment by gmoothart** [comment]
This is pretty advanced code inspection for gents to be doing; there is a *lot* of lower-hanging fruit.

I'd prefer to just tell people to annotate with `@const`. Those are converted by gents to `const` correctly.

**Comment by rkirov** [comment]
That's totally fair. Let's keep the issue open for say a quarter, because I think this is one of those issues that people keep coming back to as they use gents.

**Comment by dpurp** [comment]
tslint now handles this with the 'prefer-const' rule and supports auto-fixes, so I'm going to close this out.

https://palantir.github.io/tslint/rules/prefer-const/
