### ISSUE TITLE
Add readonly modifier to @const class fields

### ISSUE THREAD

**Issue by gmoothart** [angular/clutz#382]
When creating fields for typescript classes, any members that are annotated `@const` should have the `readonly` TS modifier added.

input:

``` javascript
/**
 * @constructor
 * @param {number} a
 */
var A = function(a) {
  /** @const {number} */
  this.a = a;
  /** @const {boolean} */
  this.b = true;
};
```

output:

``` typescript
class A {
  b: boolean = true;
  constructor(public a: number) {
  }
}
```

desired output:

``` typescript
class A {
  readonly b: boolean = true; // This work is still outstanding.

  // Adding `readonly` here has been fixed.
  constructor(public readonly a: number) {
  }
}
```

**Comment by dpurp** [comment]
I think we should be able to do add this in GentsCodeGenerator#maybeOverideCodeGen.

If I understand the AST correctly, we would need to check for a MEMBER_PROPERTY that points to CONST node in the switch.

**Comment by vpanta** [comment]
I can't tell if this is supposed to be fixed (sorry, github newbie).

But we're running into the same issue, private variables marked /** @private @const */ are not getting the readonly attribute added to them by Gents. Is that expected?

**Comment by rkirov** [comment]
It's only fixed for ctor arguments, not fields (see discussion on PR).

**Comment by rkirov** [comment]
Fixed with https://github.com/angular/clutz/commit/d3bac1d94ef32c17134357f939d25eed2667af56
