### ISSUE TITLE
gents mangles arrow functions with an implicit return

### ISSUE THREAD

**Issue by gmoothart** [angular/clutz#386]
In certain circumstances, gents is outputting an invalid function expression when it sees an arrow function.

input:
```javascript
const F = goog.defineClass(null, {
  foo: function() {},

  bar: function() {
    const baz = () => this.foo();
    return '';
  }
```

output:
```typescript
class F {
  foo() {}

  bar(): string {
    function baz() this.foo() return '';
  }
}
```

desired output:
```typescript
class F {
  foo() {}

  bar(): string {
    const baz = () => this.foo();
    return '';
  }
}
```

**Comment by dpurp** [comment]
Further investigation:

This produces valid code, but should be a fat arrow:
```javascript
/**
 * @param {number} a
 * @return {number}
 */
const arrow = a => { return a; };
```
becomes:
```typescript
function arrow(a: number): number {
  return a;
}
```

While an implicit return:
```javascript
const implicitReturnArrow = a => a;
```
becomes:
```typescript
function implicitReturnArrow(a) a
```

I suspect this is an issue with ES6 parsing in Closure Compiler.

**Comment by mprobst** [comment]
I'd suspect that the part of Gents that's trying to convert "const x =
function() ..." into "function x() ..." doesn't understand arrow functions
with no body, just appends whatever they have in that position into the
function, and then the serializer doesn't catch it (and the Node object is
untyped, so it doesn't occur).
-- 

Martin

**Comment by dpurp** [comment]
@mprobst  good guess, was able to find it right away!
