### ISSUE TITLE
gents drops @fileoverview comments

### ISSUE THREAD

**Issue by gmoothart** [angular/clutz#403]
@fileoverview jsdoc comments are dropped in gents output. I suspect it is because the comment is being tied to the top goog.module and then dropped when that node is dropped.

This may or may not be an issue when using goog.provide, we should investigate that.

input:
```
/** @fileoverview This is a file */
goog.module('A.B');
```

output:
```
<nothing>
```

desired output:
```
/** @fileoverview This is a file */
```

**Comment by mprobst** [comment]
We should maybe never remove nodes, but always just replace with an empty
node, so we retain comments?
-- 

Martin
