### ISSUE TITLE
test: compile .ts code to check validity

### ISSUE THREAD

**Issue by mprobst** [angular/clutz#404]
We should have a test that compiles the generated `.ts` code to check that we actual output valid TypeScript.

**Comment by bowenni** [comment]
Currently a lot of generated TS in our tests are broken. Even some inputs are invalid Closure code.
As a first step, we will fix the tests before compiling .ts code.

**Comment by mprobst** [comment]
We used to have an integration test that would pipe all .ts files into
TypeScript:
https://github.com/angular/clutz/blob/master/src/test/java/com/google/javascript/clutz/DeclarationSyntaxTest.java

Does that no longer run, or does it not cover enough?

**Comment by bowenni** [comment]
Still runs but only for `.d.ts`?

**Comment by mprobst** [comment]
Ah I see, I didn't get that this was specifically about `.ts` as opposed to
`.d.ts`. Makes sense.

**Comment by bowenni** [comment]
Close via #488
