### ISSUE TITLE
type aliases within goog.modules not generated correctly

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#421]
The following Closure JS module currently outputs empty declaration:

```javascript
goog.module('typealias.module');

/**
 * @typedef {{
 *   a: string,
 * }}
 */
let T;

exports.T = T;
```

**Comment by rkirov** [comment]
As a quick workaround, directly annotating the export like this works

```javascript
/**
 * @typedef {{
 *   a: string,
 * }}
 */
exports.T;
```

**Comment by rkirov** [comment]
just ran into the same problem with a default export:

```

goog.module('typealias.module');

/**
 * @typedef {{
 *   a: string,
 * }}
 */
let T;

exports = T;
```

**Comment by mprobst** [comment]
I have a pending fix for this.

**Comment by rkirov** [comment]
It appears to be fixed by https://github.com/angular/clutz/commit/89bb94edfc1b35e3b46ff15c897c059a41139656
