### ISSUE TITLE
Execution failed for :test

### ISSUE THREAD

**Issue by btgoodwin** [angular/clutz#424]
I installed gradle using SDKMAN! on CentOS 6.7 64-bit, per their instructions: `sdk install gradle 3.2`.  I then cloned clutz and attempted to build it, per the instructions: `gradle build installDist`.  The execution of `:test` failed which is preventing the build from completing.  Adding on the `--info` flag, I see this output:

    com.google.javascript.clutz.DeclarationSyntaxTest > testDeclarationUsage FAILED
        java.lang.AssertionError: [node_modules/typescript/bin/tsc, -m, commonjs, --noEmit, --skipDefaultLibCheck, --lib, es5,dom,es2015.iterable, --noImplicitAny, --strictNullChecks, src/resources/closure.lib.d.ts, src/test/java/com/google/javascript/clutz/ctor_func.d.ts, src/test/java/com/google/javascript/clutz/nested_namespaces.d.ts, src/test/java/com/google/javascript/clutz/goog_module_named_exports.d.ts, src/test/java/com/google/javascript/clutz/type_renaming_with_platform.d.ts, src/test/java/com/google/javascript/clutz/extern_ns.d.ts, src/test/java/com/google/javascript/clutz/goog_scope_templatized.d.ts, src/test/java/com/google/javascript/clutz/static_enum.d.ts, src/test/java/com/google/javascript/clutz/lends_usage.ts, src/test/java/com/google/javascript/clutz/untyped_provide.d.ts, src/test/java/com/google/javascript/clutz/goog_module_class.d.ts, src/test/java/com/google/javascript/clutz/goog_require.d.ts, src/test/java/com/google/javascript/clutz/inner_typedef_usage.ts, src/test/java/com/google/javascript/clutz/empty_type_args.d.ts, src/test/java/com/google/javascript/clutz/goog_require_usage.ts, src/test/java/com/google/javascript/clutz/record.d.ts, src/test/java/com/google/javascript/clutz/function_extends_field.d.ts, src/test/java/com/google/javascript/clutz/recursive_typedef.d.ts, src/test/java/com/google/javascript/clutz/goog_scope_usage.ts, src/test/java/com/google/javascript/clutz/goog_module_declare_legacy.d.ts, src/test/java/com/google/javascript/clutz/generics_usage.ts, src/test/java/com/google/javascript/clutz/static_inheritance_mismatch_nested_type.d.ts, src/test/java/com/google/javascript/clutz/lots_of_fn_args.d.ts, src/test/java/com/google/javascript/clutz/dict_usage.ts, src/test/java/com/google/javascript/clutz/inner_typedef.d.ts, src/test/java/com/google/javascript/clutz/union.d.ts, src/test/java/com/google/javascript/clutz/fn_params.d.ts, src/test/java/com/google/javascript/clutz/window_ext.d.ts, src/test/java/com/google/javascript/clutz/nullable_usage.ts, src/test/java/com/google/javascript/clutz/null_type.d.ts, src/test/java/com/google/javascript/clutz/enum.d.ts, src/test/java/com/google/javascript/clutz/multi_class_usage.ts, src/test/java/com/google/javascript/clutz/this_type_param_usage.ts, src/test/java/com/google/javascript/clutz/default_fn.d.ts, src/test/java/com/google/javascript/clutz/types_usage.ts, src/test/java/com/google/javascript/clutz/extern_static_namespace.d.ts, src/test/java/com/google/javascript/clutz/goog_module_legacy_named.d.ts, src/test/java/com/google/javascript/clutz/aliased_enum_usage.ts, src/test/java/com/google/javascript/clutz/default_var.d.ts, src/test/java/com/google/javascript/clutz/extern_enum.d.ts, src/test/java/com/google/javascript/clutz/tte_promise.d.ts, src/test/java/com/google/javascript/clutz/extends_function_with_platform.d.ts, src/test/java/com/google/javascript/clutz/invalid_names_usage.ts, src/test/java/com/google/javascript/clutz/provide_single_class.d.ts, src/test/java/com/google/javascript/clutz/refer_from_default_ns.d.ts, src/test/java/com/google/javascript/clutz/type_guard.d.ts, src/test/java/com/google/javascript/clutz/prototype_inferred_type.d.ts, src/test/java/com/google/javascript/clutz/inherited_default_ctor_usage.ts, src/test/java/com/google/javascript/clutz/methods_generics.d.ts, src/test/java/com/google/javascript/clutz/fn_inner_enum.d.ts, src/test/java/com/google/javascript/clutz/fn_params_usage.ts, src/test/java/com/google/javascript/clutz/undefined_type.d.ts, src/test/java/com/google/javascript/clutz/forward_declare.d.ts, src/test/java/com/google/javascript/clutz/types_externs_with_platform_usage.ts, src/test/java/com/google/javascript/clutz/extends_arraylike_with_platform.d.ts, src/test/java/com/google/javascript/clutz/reserved_var_names_usage.ts, src/test/java/com/google/javascript/clutz/invalid_names.d.ts, src/test/java/com/google/javascript/clutz/class_extends_array.d.ts, src/test/java/com/google/javascript/clutz/types.d.ts, src/test/java/com/google/javascript/clutz/inner_extern_enum.d.ts, src/test/java/com/google/javascript/clutz/static_provided.d.ts, src/test/java/com/google/javascript/clutz/interface_usage.ts, src/test/java/com/google/javascript/clutz/undefined_provide.d.ts, src/test/java/com/google/javascript/clutz/nullable.d.ts, src/test/java/com/google/javascript/clutz/reserved_var_names.d.ts, src/test/java/com/google/javascript/clutz/jsdoc.d.ts, src/test/java/com/google/javascript/clutz/static_inheritance_mismatch.d.ts, src/test/java/com/google/javascript/clutz/nested_extern_interface.d.ts, src/test/java/com/google/javascript/clutz/suppress_typecheck.d.ts, src/test/java/com/google/javascript/clutz/class_alias.d.ts, src/test/java/com/google/javascript/clutz/general_with_platform.d.ts, src/test/java/com/google/javascript/clutz/null_function_interface.d.ts, src/test/java/com/google/javascript/clutz/typealias_wrong_jsdoc.d.ts, src/test/java/com/google/javascript/clutz/enum_usage.ts, src/test/java/com/google/javascript/clutz/typedef_inner_enum.d.ts, src/test/java/com/google/javascript/clutz/types_externs_with_platform.d.ts, src/test/java/com/google/javascript/clutz/multi_provides.d.ts, src/test/java/com/google/javascript/clutz/nested_namespaces_ext.d.ts, src/test/java/com/google/javascript/clutz/generics.d.ts, src/test/java/com/google/javascript/clutz/inherited_default_ctor.d.ts, src/test/java/com/google/javascript/clutz/default_var_usage.ts, src/test/java/com/google/javascript/clutz/index_signature_with_platform.d.ts, src/test/java/com/google/javascript/clutz/lends.d.ts, src/test/java/com/google/javascript/clutz/base.d.ts, src/test/java/com/google/javascript/clutz/default_fn_usage.ts, src/test/java/com/google/javascript/clutz/privates.d.ts, src/test/java/com/google/javascript/clutz/type_alias.d.ts, src/test/java/com/google/javascript/clutz/provide_single_class_usage.ts, src/test/java/com/google/javascript/clutz/nested_namespaces_usage.ts, src/test/java/com/google/javascript/clutz/static_provided_usage.ts, src/test/java/com/google/javascript/clutz/extending_function_field.d.ts, src/test/java/com/google/javascript/clutz/aliased_enums.d.ts, src/test/java/com/google/javascript/clutz/private_type.d.ts, src/test/java/com/google/javascript/clutz/goog_scope.d.ts, src/test/java/com/google/javascript/clutz/interface.d.ts, src/test/java/com/google/javascript/clutz/this_type_param.d.ts, src/test/java/com/google/javascript/clutz/provide_instance.d.ts, src/test/java/com/google/javascript/clutz/forward_declare_usage.ts, src/test/java/com/google/javascript/clutz/enum_unprovided.d.ts, src/test/java/com/google/javascript/clutz/type_used_but_not_provided.d.ts, src/test/java/com/google/javascript/clutz/multi_provides_usage.ts, src/test/java/com/google/javascript/clutz/abstract_method.d.ts, src/test/java/com/google/javascript/clutz/dict.d.ts, src/test/java/com/google/javascript/clutz/record_usage.ts, src/test/java/com/google/javascript/clutz/multi_class.d.ts, src/test/java/com/google/javascript/clutz/tte_promise_usage.ts, src/test/java/com/google/javascript/clutz/type_alias_usage.ts]: exited abnormally with code 1
        src/test/java/com/google/javascript/clutz/reserved_var_names.d.ts(6,18): error TS2503: Cannot find namespace 'alias'.
        src/test/java/com/google/javascript/clutz/reserved_var_names.d.ts(10,18): error TS2503: Cannot find namespace 'alias'.
            at org.junit.Assert.fail(Assert.java:88)
            at com.google.javascript.clutz.DeclarationSyntaxTest.runChecked(DeclarationSyntaxTest.java:137)
            at com.google.javascript.clutz.DeclarationSyntaxTest.doTestDeclarationUsage(DeclarationSyntaxTest.java:123)
            at com.google.javascript.clutz.DeclarationSyntaxTest.testDeclarationUsage(DeclarationSyntaxTest.java:105)
    Gradle Test Executor 1 finished executing tests.

    137 tests completed, 1 failed
    Finished generating test XML results (0.009 secs) into: /home/temp/Downloads/temp/clutz/build/test-results/test
    Generating HTML test report...
    Finished generating test html results (0.017 secs) into: /home/temp/Downloads/temp/clutz/build/reports/tests/test
    :test FAILED
    :test (Thread[Daemon worker Thread 2,5,main]) completed. Took 24.294 secs.

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':test'.
    > There were failing tests. See the report at: file:///home/temp/Downloads/temp/clutz/build/reports/tests/test/index.html

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

    BUILD FAILED

    Total time: 26.986 secs
    Stopped 0 compiler daemon(s).
    Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':test'.] from daemon DaemonInfo{pid=72556, address=[8386e201-c19c-4d4c-b155-6885416c1065 port:38528, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1479225224639, context=DefaultDaemonContext[uid=976c83b3-eb5b-48c4-8edb-757554428d7b,javaHome=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.111.x86_64,daemonRegistryDir=/home/temp/.gradle/daemon,pid=72556,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).

According to the error it couldn't find the namespace `alias`.  What is the work-around for this?

**Comment by dpurp** [comment]
hmm.. the tests seem to be passing on Travis.  I wonder if this is environment specific.

https://travis-ci.org/angular/clutz

**Comment by traviskaufman** [comment]
This was failing for me as well, but then I ran `npm install clang-format` in the root clutz dir, and then all tests passed.

**Comment by ayusun** [comment]
I am also facing the same issue, nay update on this?

**Comment by mprobst** [comment]
The problem here was probably that @btgoodwin was using a different TypeScript version from what's required. The fix is to run `npm install` in the clutz root directory.

**Comment by rkirov** [comment]
see https://github.com/angular/clutz/issues/594#issuecomment-387573566 for the 'reserved_var_names.d.ts' mystery.
