### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by thorn0** [angular/clutz#428]
Trying to build this project (current `master`), I get a lot of failing tests where the difference between the expected and the actual boils down to white spaces. Like this:
```
com.google.javascript.gents.TypeScriptGeneratorTests > typedef.js FAILED
    org.junit.ComparisonFailure: expected:<...type MyInterface = {[
      x: string,
      y: number
    };
    let x: MyString = 'x'];
    > but was:<...type MyInterface = {[x:string, y:number};
    let x: MyString = "x"];
    >
```
137 tests completed, 121 failed
Windows 7 x64, Java 1.8.0_66, Node 6.9.1, Gradle 3.2

I've run `npm install` before `gradle build installDist`.

Probably this issue should be closed, and #363 reopened.

**Comment by thorn0** [comment]
It starts to find `clang-format` if I change `gents.clangFormat` in `build.gradle` from `node_modules/.bin/clang-format` to `node_modules\\.bin\\clang-format.cmd`. However, many other tests still fail (137 tests completed, 94 failed).

Examples:
```
com.google.javascript.clutz.MultiFileTest > shouldResolveNamedTypes FAILED
    org.junit.ComparisonFailure: compilation result doesn't match expected:<[declare namespace ?_?.clutz.namedType {
      class A < U > extends A_Instance < U > {
      }
      class A_Instance < U > {
        private noStructuralTyping_: any;
        fn (a : ?_?.clutz.namedType.D < any > ) : any ;
      }
    }
    declare namespace goog {
      function require(name: 'namedType.A'): typeof ?_?.clutz.namedType.A;
    }
    declare module 'goog:namedType.A' {
      import alias = ?_?.clutz.namedType.A;
      export default alias;
    }
    declare namespace ?_?.clutz.namedType {
      class D < T > extends D_Instance < T > {
      }
      class D_Instance < T > {
        private noStructuralTyping_: any;
      }
    }
    declare namespace goog {
      function require(name: 'namedType.D'): typeof ?_?.clutz.namedType.D;
    }
    declare module 'goog:namedType.D' {
      import alias = ?_?.clutz.namedType.D;
      export default alias;
    }
    ]> but was:<[]>
        at com.google.common.truth.Platform.comparisonFailure(Platform.java:133)
        at com.google.common.truth.Truth$1.failComparing(Truth.java:69)
        at com.google.javascript.clutz.ProgramSubject.generatesDeclarations(ProgramSubject.java:72)
        at com.google.javascript.clutz.MultiFileTest.shouldResolveNamedTypes(MultiFileTest.java:38)
```

```
com.google.javascript.gents.TypeScriptGeneratorMultiTests > module_imports FAILED
    java.lang.AssertionError: Not true that <{}> has a size of <8>. It is <0>

com.google.javascript.gents.TypeScriptGeneratorMultiTests > provide_imports FAILED
    java.lang.AssertionError: Not true that <{}> has a size of <4>. It is <0>

com.google.javascript.gents.TypeScriptGeneratorMultiTests > type_rewrite FAILED
    java.lang.AssertionError: Not true that <{}> has a size of <5>. It is <0>
```

**Comment by mprobst** [comment]
This sounds like you have a different clang-format version installed than expected, and formatting fails, which then means either the code looks odd, or it seems that all results are empty. It's sadly a bit of a pain to get clang-format installed and available on all platforms in the right version, sorry :-(

Can you check what version of clang-format you have installed?

Also, can you debug through the unit test to see if the clang-format execution actually happens, and has the expected result?

**Comment by gregbown** [comment]
The build cannot find or access clang-format.  It has the same result even if the path is empty quotes.  The results are the same running gradle from eclipse or npm
`tasks.withType(Test) {
  systemProperty 'gents.clangFormat',
                 System.getProperty('gents.clangFormat', '')
}`
I have tried absolute paths etc. Nothing makes any difference. I tried setting a system path as well.  I am able to run clang-format -help as well as gradle -help from cmd so I know the environmental path is correct

**Comment by gregbown** [comment]
Also many of the tests fail due to a compilation error?
com.google.javascript.clutz.MultiFileTest > depgraph FAILED
    org.junit.ComparisonFailure: compilation result doesn't match expected:<[declare namespace ?_?.clutz.root {
      class Z extends Z_Instance {
      }
      class Z_Instance {
        private noStructuralTyping_: any;
        useTransitive ( ) : ?_?.clutz.transitive.Y | null ;
        useTransitiveNamespaced ( ) : ?_?.clutz.transitive.ns.Z | null ;
      }
    }
    declare namespace goog {
      function require(name: 'root.Z'): typeof ?_?.clutz.root.Z;
    }
    declare module 'goog:root.Z' {
      import alias = ?_?.clutz.root.Z;
      export default alias;
    }
    declare namespace ?_?.clutz.transitive {
      class Y extends Y_Instance {
      }
      class Y_Instance {
        private noStructuralTyping_: any;
      }
    }
    declare namespace ?_?.clutz.transitive.ns {
      class Z extends Z_Instance {
      }
      class Z_Instance {
        private noStructuralTyping_: any;
      }
    }
    ]> **but was:<[]>**
        at com.google.common.truth.Platform.comparisonFailure(Platform.java:126)
        at com.google.common.truth.Truth$1.failComparing(Truth.java:70)
        at com.google.javascript.clutz.ProgramSubject.generatesDeclarations(ProgramSubject.java:70)
        at com.google.javascript.clutz.MultiFileTest.depgraph(MultiFileTest.java:69)

**Comment by mprobst** [comment]
The problem is just that it cannot execute clang-format for some reason. I'd recommend attaching a debugger and seeing what command it's trying to execute.

**Comment by gregbown** [comment]
Finally got this to work [documented here](https://github.com/angular/clutz/issues/363)
