### ISSUE TITLE
Gents errors on destructured imports outside of the project

### ISSUE THREAD

**Issue by dpurp** [angular/clutz#447]
ERROR - Module goog.object.getKeys does not exist.
  12| const {getKeys} = goog.require('goog.object');
  13| const {sortByKey} = goog.require('goog.array');

ERROR - Module goog.array.sortByKey does not exist.
  12| const {getKeys} = goog.require('goog.object');
  13| const {sortByKey} = goog.require('goog.array');
  14|

**Comment by rkirov** [comment]
'outside the project' meaning goog.object and goog.array source files are passed to gents or not?

**Comment by dpurp** [comment]
The source files are passed with the manifest, but they are not included in gents "prefixes-to-convert".

**Comment by rkirov** [comment]
I haven't seen such an issue recently, so I am assuming it has been fixed.
