### ISSUE TITLE
Gents: strip local variable type annotations

### ISSUE THREAD

**Issue by mprobst** [angular/clutz#450]
Gents currently leaves them in:

```ts
/** @type {boolean} */
let b = false;
```

**Comment by gmoothart** [comment]
I think we need a more specific repro (does the type annotation span multiple lines?). This tests that the annotation is removed:

https://github.com/angular/clutz/blob/master/src/test/java/com/google/javascript/gents/singleTests/comments.js

**Comment by dpurp** [comment]
If I remember correctly, this doesn't work for inline types.

**Comment by mprobst** [comment]
For Googlers, this happened in cr/145585604.

**Comment by gmoothart** [comment]
@mprobst is that the right cl? I see an instance of "@type" in zippy.ts which is correctly removed, and none that aren't.

**Comment by mprobst** [comment]
Mh. Maybe I'm confused. Try looking at the blame lines at head?

Gabe Moothart <notifications@github.com> schrieb am Di., 28. Feb. 2017 um
20:50 Uhr:

**Comment by gmoothart** [comment]
Looks like this is working correctly.
