### ISSUE TITLE
class with inner typedef makes gents die

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#451]
From @andresdominguez

```javascript
goog.module('foo.bar');

class C {...}
/**
 * @typedef {{
 *     scalarType: string
 * }}
 */
C.Type = {};

exports = C;
```

makes gents throw.

**Comment by bowenni** [comment]
TODO:
Rename references across multiple files.
Include typedefs' function types in TypeScript interfaces too.
Convert typedefs that are not inside a class to interfaces too.

**Comment by bowenni** [comment]
Closing the main bug. https://github.com/angular/clutz/pull/471 handles the renaming references across multiple files.

Opening https://github.com/angular/clutz/issues/482 to track the related low priority task.
