### ISSUE TITLE
Closure's plain Object type should translate to `{[key: string]: any}` not just TS Object

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#469]
Object in typescript does not have index signature by default, and it triggers noImplicitAny errors. However, in closure index access is allowed and a large number of Object usages are to model maps from strings to any type values.

The downside of this approach is that sometimes it can be preferable to leave the noImplicitAny error, to trigger the user to check the code and put in the proper value type.

**Comment by rkirov** [comment]
On the flip side, even accessing fields on Object is just a warning, so maybe it should just translate to `any`

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%2520%2540const%2520%257BObject%257D%2520*%252F%250Alet%2520x%2520%253D%2520%257B%257D%253B%250A%250Ax.foo%253B

**Comment by mprobst** [comment]
I think that accessing any fields on Object is legal due to Closure's lax property access checking (it kind of assumes you know what you're doing there). I think we should not expose that to TS users, `{[k: string]: Something}` sounds good, and `:any` for a naked object SGTM, too.

**Comment by rkirov** [comment]
Currently, we use the `externs_map.json` to make all `Object` types `AnyDuringMigration`. The map makes it easy to adjust what we want the output to be.
