### ISSUE TITLE
Convert typedefs to interfaces

### ISSUE THREAD

**Issue by bowenni** [angular/clutz#482]
For example [this](https://github.com/angular/clutz/blob/7e44625e0d82340d8371536d49525f8323481369/src/test/java/com/google/javascript/gents/multiTests/goog_provide_rewrite/goog_scope.js#L88-L93) should be [an interface](http://www.typescriptlang.org/play/#src=interface%20PrivateTypedef_%20%7B%0D%0A%20%20myFunction%3A%20(p1%3A%20any)%20%3D%3E%20PrivateTypedef_%0D%0A%7D) rather than a [type alias](https://github.com/angular/clutz/blob/7e44625e0d82340d8371536d49525f8323481369/src/test/java/com/google/javascript/gents/multiTests/goog_provide_rewrite/goog_scope.ts#L60-L62)

**Comment by rkirov** [comment]
Fixed with https://github.com/angular/clutz/commit/b648e4c8adfe80c02540960a9ee992d82074ee76
