### ISSUE TITLE
gents should remove goog.inherits calls

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#484]

**Comment by bowenni** [comment]
Should gents also remove goog.bind calls?
https://github.com/angular/clutz/blob/94d5e77e010af6546e6a41917ff9f7768f046c7c/src/test/java/com/google/javascript/gents/singleTests/undeclared_property.ts#L6

**Comment by rkirov** [comment]
`goog.bind(function() {...}, arg1, arg2)` can be replaced with `(function(){...}).bind(arg1, arg2)`, and I think then a ts lint pass can make replace `(function () {}).bind(this)` to `() => {}`.

**Comment by rkirov** [comment]
fn.bind can do partial application too, which cannot be replaced with just `() => {}`

**Comment by stringham** [comment]
@rkirov I believe goog.inherits calls are already removed if the `extends` is resolved to a valid name:

https://github.com/angular/clutz/blob/master/src/main/java/com/google/javascript/gents/TypeConversionPass.java#L651

However, this function returns early if it logs an error.

**Comment by rkirov** [comment]
Ops, I should have written down the code that produced the bad result. Too long has passed since then, so I am just going to close the bug.
