### ISSUE TITLE
Improve return type as a type guard for goog.isDefAndNotNull and other goog.is* function?

### ISSUE THREAD

**Issue by danielscottjames** [angular/clutz#518]
Currently for these functions (`isDefAndNotNull`, `isNull`, `isArray`, etc..) the definition generated looks like, 
`function isDefAndNotNull (val : any ) : boolean ;`

It would be nice if it used TypeScript's Type Guard feature, something like:
`function isDefAndNotNull<T> (val : T | null | undefined ) : val is T ;`

This is particularly helpful when using TypeScript's `strictNullCheck` flag
```
function example(arg?: Something) {
    if (goog.isDefAndNotNull(arg)) {
        arg.doSomething(); // Error, object is possibly undefiend
    }

    // ...
}
```

Is this possible or special-casable or configurable?

Thanks!

**Comment by rkirov** [comment]
Indeed a `val is T` translation would be much more useful in TypeScript. However, they will have to be one-offs and hardcoded. I think in generally it might be worth doing, but low on my priority list. Also I am only ok with functions from goog.base that don't change too often.

I have a bias that I find `isDefAndNotNull` and similar one-liners actually not useful. Just using `val != null` is less characters, requires no import, no clutz, etc.

**Comment by mprobst** [comment]
I think using `isNull` and `isDefAndNotNull` is generally discouraged these days, even in JS code. Just use `!= null` and `!== null` as appropriate. With that, I agree with Rado, not worth fixing.
