### ISSUE TITLE
gents: Error - Invalid superclass for Foo

### ISSUE THREAD

**Issue by stringham** [angular/clutz#524]
I have a JavaScript file, `foo.ts` with the following contents:

```javascript
goog.provide('lucid.Foo');

goog.require('goog.events.EventTarget');

/**
 * @constructor
 * @extends {goog.events.EventTarget}
 */
lucid.Foo = function() {
    lucid.Foo.base(this, 'constructor');
};
goog.inherits(lucid.Foo, goog.events.EventTarget);

lucid.Foo.prototype.change = function() {
    this.dispatchEvent('Changed!');
};
```

when I run gents on it, I get this error:

```
app/webroot/js/app/apps/foo.js:12: ERROR - Invalid superclass for Foo
  10|     lucid.Foo.base(this, 'constructor');
  11| };
  12| goog.inherits(lucid.Foo, goog.events.EventTarget);
  13| 
  14| lucid.Foo.prototype.change = function() {
```

and the generated typescript looks like:

```typescript
import EventTarget from 'goog:goog.events.EventTarget';

export class Foo extends goog.events.EventTarget {
  constructor() {
    super();
  }

  change() {
    this.dispatchEvent('Changed!');
  }
}
goog.inherits(Foo, EventTarget);
```

It seems to properly alias `goog.events.EventTarget` everywhere except in the `extends` statement.

**Comment by Dan1ve** [comment]
Any insights about this issue?
I'm seeing this error as well, with a very simple example of two classes (x.y.ClassA and x.y ClassB, where the second class inherits from the first one)

**Comment by chivesrs** [comment]
+1, ran into this issue as well

**Comment by rkirov** [comment]
We are making gents focus on ES6 input and relying on other tools to do the ES5->ES6 transformation.

**Comment by joswhite** [comment]
+1. Anyone have a valid workaround?

**Comment by joswhite** [comment]
@rkirov Is there any tool I might be able to use to do the ES5->ES6 transformation so I can get around this issue? I have about 140 of these errors in just trying to convert the Closure library portion we are using in our code base. Or, do you know of a workaround so I can still use gents without having this issue?

**Comment by Dan1ve** [comment]
@joswhite We recently converted the Closure library to ES6, so maybe this will be helpful for you? https://github.com/DreierF/ts-closure-library

**Comment by rkirov** [comment]
Unfortunately, the tools we use in Google for the ES5->ES6 conversion are not open-sourced and we don't have plans to do so.

If you are talking about converting the Closure library itself, 'gents' is not the tools for that job. The goal of gents is "one-time" conversion, after which the .js code can be deleted. As it doesn't currently get you 100% there that's ok because one can fix the output with some manual edits. If you need continuous translation of a library that keeps on changing like Closure Library, I think gents will not fit your needs.

@Dan1ve we were wondering if you used any of our tools - clutz or gents for that conversion or something home-grown?

**Comment by Dan1ve** [comment]
@rkirov No. We needed both ES6 classes + ES6 modules, and AFAIK there was no easy way to get there with existing tools. All we could to was a semi-automated conversion, i.e., a lot of manual work. (We also have some scripts to allow updating the Closure lib and re-applying older fixes).
We plan to write a blog post with some details about this pretty soon 😉 

We _do_ use `gents` for converting our own code from (Closure-typed, ES6) Javascript to Typescript and this works quite nicely (with a couple of manual fixes per file).

**Comment by joswhite** [comment]
Thank you!

**Comment by evmar** [comment]
@Dan1ve did you end up writing that blog post?  We'd like to see it!

**Comment by Dan1ve** [comment]
@evmar not yet, but I have a draft. I'll keep you in the loop!
