### ISSUE TITLE
exporting an object literal can be translated better than default exports

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#527]
This pattern

```javascript
goog.module('a.b.c');
const x = 0;
exports = {x: x};
```

is translated to 

```javascript
const x = 0;

export const c = {
  x: x
};
```

Because that is how gents handles default exports in general.

However, this output would be preferable and closer to the original intent: 

```javascript
export const x = 0;
```

Clearly, this can only be done for static object literal with a simple `{nameA: nameA, nameB: nameB}` (names need to match in order to maintain export symbol).

Reported by @mgr01, from what I hear this is common enough to be worth the extra effort in rewriting.

**Comment by rkirov** [comment]
Note that if the code was written as:

```javascript
goog.module('a.b.c');
const x = 0;
exports.x = x;
```

the indented translation is achieved.

**Comment by aluanhaddad** [comment]
Also note that this is not a `default` export.
