### ISSUE TITLE
Static methods on @enum {number} get dropped

### ISSUE THREAD

**Issue by takamori** [angular/clutz#540]
If you have the following code, the static method `my.Fruit.getDebugColor` gets dropped in the typings file output by clutz, which results in an error when trying to use it from TypeScript code.
```
/** @enum {number} */
my.Fruit = {
  APPLE: 0,
  PEAR: 1
};

/**
 * @param {my.Fruit} fruit
 * @return {string} A color for debugging.
 */
my.Fruit.getDebugColor = function(fruit) {
  switch (fruit) {
    case my.Fruit.APPLE: return 'red';
    case my.Fruit.PEAR: return 'green';
    default: return 'invisible';
  }
};
```

It would be helpful to address this case somehow for users who are converting to TypeScript.

**Comment by mprobst** [comment]
Given that we're moving closer to use proper TypeScript enums, for the type checking benefits, I think this is infeasible as long as TS doesn't support methods on enums. See #546.

**Comment by rkirov** [comment]
Once we move to proper TS enums, we can emit an enum + namespace pair like this:

```typescript
declare enum X {
  A,
  B
}
declare namespace X {
  function foo(): void;
}
```
But it is not of high priority at this point. Will reopen the bug if we end up working on it.
