### ISSUE TITLE
gents doesn't generate the right destructuring imports

### ISSUE THREAD

**Issue by CyberjujuM** [angular/clutz#573]
Gents transforms:

const {a, b, c, d, e} = goog.require('my.project.core.constants');

into:

import {a} from './core/constants';

Anything after "a" is dropped.

**Comment by bowenni** [comment]
I think this is https://github.com/angular/clutz/issues/392
There's a [TODO](https://github.com/angular/clutz/blob/8eb366ce96efb95ed60a8cd8a0e57ff4ab7147bc/src/main/java/com/google/javascript/gents/ModuleConversionPass.java#L232)
