### ISSUE TITLE
Should DeclarationGenerator be public?

### ISSUE THREAD

**Issue by whymarrh** [angular/clutz#589]
The README notes:

> You can use Clutz as a library from a Java based build, or execute the wrapper script produced by Gradle.

If the library should be usable from via Java, should `DeclarationGenerator` be made public?

**Comment by mprobst** [comment]
I think what we mean to say is that you can execute this using `java ...` on the command line. Not sure though.

Do you want/need this to be a Java-callable API? What should the API look like, if so?

**Comment by whymarrh** [comment]
> Do you want/need this to be a Java-callable API? What should the API look like, if so?

The current command line interface works for me but I was sent down a path thinking that I would be able to use it as a Java library because of how I had interpreted that description.

> I think what we mean to say is that you can execute this using java ... on the command line. Not sure though.

Would you be open to a clarifying edit to the README to make that section something along the lines of "you can use Clutz by executing the built JAR or by executing the wrapper shell script produced by Gradle"?

**Comment by mprobst** [comment]
Clarifying docs sounds good to me.
