### ISSUE TITLE
Incremental clutz fails for Closure timezonelist.js that doesn't provide its types

### ISSUE THREAD

**Issue by evmar** [angular/clutz#599]
```js
/** @suppress {extraProvide} */
goog.provide('goog.locale.TimeZoneList');

goog.require('goog.locale');

goog.locale.foo = ...;
goog.locale.bar = ...;
```

we need types for `goog.locale.foo` etc even though the file doesn't provide them.

Symptom: can't use `goog.locale.foo` .

**Comment by mprobst** [comment]
I think this particular file gave us trouble before.

Can we maybe just fix the source?

**Comment by evmar** [comment]
Fixed in the source.
