### ISSUE TITLE
Gents should convert `function(){...}.bind(this)` to arrow functions

### ISSUE THREAD

**Issue by dpurp** [angular/clutz#600]
If the contents of the function uses `this`, TypeScript errors unless a `this` is defined as an arg in the function.

Since we ultimately want to switch arrow functions (per tslint rules), gents should just do this for us to decrease the time needed to switch legacy code to TypeScript.

**Comment by rkirov** [comment]
We have this fixer outside gents, written on top of the TS AST. There is no benefit that I see in doing in gents, as it doesn't need to parse Closure types. We want Gents to be focused on things that have to do with Closure JSDOC types only.
