### ISSUE TITLE
Incremental clutz gets wrong type on Thenable.then

### ISSUE THREAD

**Issue by evmar** [angular/clutz#601]
closure/promise/thenable.js has a complex type and some TTL for its .then() method, and Clutz has some special-casing around it.  Maybe this special-casing isn't firing for incremental?  The generated d.ts just has

```ts
    then (opt_onFulfilled : any , opt_onRejected : any , opt_context : any ) : any ;
```

where importantly we lose that the arguments are optional.

**Comment by rkirov** [comment]
Couldn't repro on the clutz repro - https://github.com/rkirov/clutz/tree/tte 

Going to try on the external tests.

Also code handling TTE is completely contained here - https://github.com/angular/clutz/blob/4ccbc8c4349c66d97f599518c2fad02dc2de1e9b/src/main/java/com/google/javascript/clutz/DeclarationGenerator.java#L2437

**Comment by evmar** [comment]
I am full of lies.  This one is just a dup of #552.  I got my files confused.
