### ISSUE TITLE
Incremental Clutz refers to wrong Date in DateLike

### ISSUE THREAD

**Issue by evmar** [angular/clutz#602]
DateLike looks like:

```js
goog.forwardDeclare('goog.date.Date');

/**
 * @typedef {(Date|goog.date.Date)}
 */
goog.date.DateLike;
```

The reference to `Date` there is attempting to reference the global Date, but it ends up picking up the forward-declared `goog.date.Date` from the current namespace.

**Comment by evmar** [comment]
Errors end up looking like:

```
Argument of type 'Date' is not assignable to parameter of type 'DateLike'.
```

**Comment by rkirov** [comment]
This is odd because by the description it should be broken in non-incremental clutz too, but actually it is not.

**Comment by evmar** [comment]
iclutz output:

```js
// datelike.d.ts
//!! Processing provides [goog.date.DateLike] from input javascript/closure/date/datelike.js
declare namespace ಠ_ಠ.clutz.goog.date {
  type DateLike = Date | null | ಠ_ಠ.clutz.goog.date.Date ;
}

// date.d.ts
declare namespace ಠ_ಠ.clutz.goog.date {
  class Date extends Date_Instance {
```

In normal Clutz I see no mention of DateLike in the d.ts.  It appears normal clutz is expanding the alias.

**Comment by rkirov** [comment]
Ah, actually, we do a how pass to undo type alias expansion, but maybe other bugs are prevent that from happening with 'DateLike'.

Anyways, the solution is to add 'Date' to the list of types that will be renamed to 'GlobalDate'

https://github.com/angular/clutz/blob/4ccbc8c4349c66d97f599518c2fad02dc2de1e9b/src/main/java/com/google/javascript/clutz/DeclarationGenerator.java#L232

and also added to 'closure.lib.d.ts' https://github.com/angular/clutz/blob/4ccbc8c4349c66d97f599518c2fad02dc2de1e9b/src/resources/closure.lib.d.ts#L5

**Comment by rkirov** [comment]
Another mystery here with comparison to https://github.com/angular/clutz/issues/598, is why do we emit: 
`  type DateLike = Date | null | ಠ_ಠ.clutz.goog.date.Date ;` and not
`  type DateLike = ಠ_ಠ.clutz.Date | null | ಠ_ಠ.clutz.goog.date.Date ;`
given that incremental clutz doesn't even pass externs to its run.
