### ISSUE TITLE
Union of two unresolved types is optimized into a single type

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#625]
```javascript
/**
 * @param {Foo|Bar} a
 */
```

is emitted as `a: Foo`

This is a closure bug, so it would be best to fix in closure.

**Comment by LucasSloan** [comment]
Fix was submitted in closure today, but probably not in the public repo (and thus maven) for a bit.

**Comment by rkirov** [comment]
New closure release is out - https://mvnrepository.com/artifact/com.google.javascript/closure-compiler/v20180101
