### ISSUE TITLE
Gents does not translate `@record` correctly

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#627]

**Comment by cbelden** [comment]
This was essentially the input:

```
goog.module('some.module.MyRecord');


/** @record */
class MyRecord {}

/** @const {boolean} */
MyRecord.prototype.someProperty;

exports = MyRecord;
```

And the emitted TypeScript was:

```
export class MyRecord {
  someProperty: boolean;
}
```

And the expected TypeScript was:

```
export interface MyRecord {
  someProperty: boolean;
}
```

**Comment by dpurp** [comment]
I think this is working as intended.

If I understand correctly `class MyRecord` should be `function MyRecord` for JSCompiler to treat this as an interface rather than a class.

**Comment by rkirov** [comment]
Ops, I did not notice the funky `@record` and `class` pattern. Yeah, TS has to pick one and 'class' is the more natural choice. It think this should be corrected by the user in this case where really the original intent was '@record' but `class` was used instead of `function`.

**Comment by mprobst** [comment]
David: are you sure? I think the YT guys might be correct about this being
a legal way to define an interface (after all, `@record` on a `function`
doesn't make any more sense than on a class...).

**Comment by rkirov** [comment]
I keep switching around on this. For a second my reasoning was that emitting a class is the safer option because gents doesn't know if the class is used as ctor anywhere with `new C()` or it has some static members. But it appears closure rejects the ctor usage, while allowing the statics :/

**Comment by evmar** [comment]
My opinion: if the person went to the trouble to write out @interface or @record on top of their 'class', then we should obey that annotation over the class.  It's true it's possible to have "@record class C { static X; }" which would then produce illegal TS but that arguably should be illegal on the JS side anyway and it's fine to make the user manually correct it.

**Comment by dpurp** [comment]
> are you sure?

Well, if it's not erring on the JS side, then I guess not.  It definitely seems like a surprising pattern to me.

It seems strange for an interface to have a constructor, as it does with `class.` The documentation does say that if `new` is used with `@record` a warning is thrown.
https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#interface-record

Stepping back a bit, regardless of whether this is correct syntax, if this is a common pattern, as @evmar said, annotating with`@record` does seem like a pretty strong signal for interface and maybe we should just make it do the right thing, regardless.

**Comment by rkirov** [comment]
On the flip side again, classes *can* be used as interfaces in TS, but it is an odd thing to rely on (because of the requirement for methods to have implementations). Also in the majority of the code we are seeing in YT is purely interfaces

```typescript
class C {foo():void {}}
class D implement C {foo(): {}}
```

**Comment by rkirov** [comment]
Fixed with https://github.com/angular/clutz/commit/7f940d255c2c8c289e7bb76b523c7daf01288907#diff-b6c0cace83cf249db2147e1abe17713d
