### ISSUE TITLE
gents drops the type when the function has default args

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#631]
```javascript
/**
 * @param {boolean=} a
 */
function f(a = undefined)
```
Produces `function(a = undefined)` but should be `function(a: boolean|undefined = undefined)`

**Comment by rkirov** [comment]
Alternatively, it can be `function(a?: boolean)` and rely on the implicit `undefined`. I think these is no difference? 

cc @evmar

**Comment by evmar** [comment]
a? means you can call with no args, at least in TS that is different than a|undefined.

**Comment by rkirov** [comment]
But when you have a default arg '= undefined' that difference is gone. I am trying to think if the runtime assignment of unconditional undefined matters in the second case.
