### ISSUE TITLE
Gents crashes on hello world

### ISSUE THREAD

**Issue by theRobinator** [angular/clutz#633]
I originally tried gents on my Closure-annotated project and it crashed on the first line of code. I tried to create a minimal reproduction, and ended up with this. I'm running OSX 10.11.6, Java 1.8.0_121.

```
Robin$ cat test.js
console.log('hello world!');
Robin$ 
Robin$ gents test.js
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.google.javascript.gents.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:147)
	at com.google.javascript.gents.TypeScriptGenerator.main(TypeScriptGenerator.java:75)
Uncaught exception in gents, exiting.
```

Interestingly, if I specify `-o somedir`, correct output is still written to that directory. However, that seems to only work for some files -- the files in my project don't produce any output at all.

**Comment by rkirov** [comment]
It's because of --rewriteLog that we end up always using in Google. Fix coming.

**Comment by theRobinator** [comment]
Thanks!
