### ISSUE TITLE
incremental clutz and typedef vs object type ambiguation

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#638]
When incremental clutz sees:
```javascript
/** @const {Foo} */
```
It assumes `Foo` is object types so the correct translation would be `: Foo | null`, however if `Foo` was a typedef `/** @typdef {!Bar} */ let Foo`, the correct translation would be just `Foo` (or even just `Bar`).

**Comment by rkirov** [comment]
Maybe enums have the same issue.

**Comment by rkirov** [comment]
Options:
- emit all typedefs and enums as nullable.
- have a hardcoded list of exceptions
- tell users to write `@const {!Foo}`

**Comment by evmar** [comment]
My work in progress has some tests:
https://github.com/angular/clutz/compare/nullable

**Comment by rkirov** [comment]
closing this as decided to fix in user code by adding '!' when needed.
