### ISSUE TITLE
incremental clutz should handle "class aliases" better

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#640]
This happens in closure's default lib

```javascript
goog.provide('goog.log.Level');

goog.require('goog.debug.Logger');


/**
 * @constructor
 * @final
 */
goog.log.Level = goog.debug.Logger.Level;
```

We emit an empty class ```class Level {}``` (with the usual _Instance etc), when debug.Logger is not part of the compilation. It would be better to detect and emit `type Level = any; var Level: any`, so that the type and value are usable.

Even better if we can stitch it back with `goog.debug.Logger.Level` emit maybe by extends - `class Level extends goog.debug.Logger.Level {}`.

**Comment by LucasSloan** [comment]
Fixed by #644
