### ISSUE TITLE
Do not emit empty constructors.

### ISSUE THREAD

**Issue by bowenni** [angular/clutz#647]
Another frequently seen pattern from code reviews:

Given this code
```js
class C extends B {
  constructor() {
    super();
    /** @private {number} */
    this.a = 1;
  }
}
```
We emit
```js
class C extends B {
  private a: number = 1;

  constructor() {
    super();
  }
}
```
which can be simply
```js
class C extends B {
  private a: number = 1;
}
```
But I guess this can be achieved much easier and cleaner by a post-migration TSLint fixer.

**Comment by rkirov** [comment]
I agree, that this will be easier to in TSlint, as it has little to do with Closure.
