### ISSUE TITLE
Default nullability of object types is wrong?

### ISSUE THREAD

**Issue by bowenni** [angular/clutz#649]
According to [Closure Compiler wiki](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#nullable-type), object types are nullable by default.
However this code
```js
class C {
  /** @param {Foo} p */
  constructor(p) {}
}
```
gets migrated to
```js
class C {
  constructor(p: Foo) {} // p is not nullable
}
```

**Comment by rkirov** [comment]
This ambiguity has been resolved on the Closure side, requiring people to write `{?Foo}` or `{!Foo}` and declaring bare `{Foo}` wrong style.
