### ISSUE TITLE
Enum lost when aliasing

### ISSUE THREAD

**Issue by evmar** [angular/clutz#669]
```js
goog.module('enum_alias');

const OtherEnum = goog.require('not_visible');

/** @enum {string} */
const Enum = OtherEnum;

exports = Enum;
```

Produces 
```js
  var module$exports$enum_alias : any ;
```
which loses that `Enum` is also usable as a type.

**Comment by rkirov** [comment]
I wonder why, the code that make this test work, doesn't work here -

https://github.com/angular/clutz/blob/master/src/test/java/com/google/javascript/clutz/aliased_enums.js

**Comment by rkirov** [comment]
Played a bit more with this example. One observation is that when it is a named export the emit is fine, which could be a fine workaround.

**Comment by evmar** [comment]
Not in this case, because that changes the shape of the module -- right now the entire exports object is the enum.
