### ISSUE TITLE
`gradle build installDist` fails with test failures

### ISSUE THREAD

**Issue by awk** [angular/clutz#708]
Using the current 'HEAD' there appears to be one failure in the clutz tests:

```
com.google.javascript.clutz.DeclarationSyntaxTest > testDeclarationUsage FAILED
    java.lang.AssertionError: tsc exited abnormally with code 1
    src/test/java/com/google/javascript/clutz/reserved_var_names.d.ts(6,18): error TS2503: Cannot find namespace 'alias'.
    src/test/java/com/google/javascript/clutz/reserved_var_names.d.ts(10,18): error TS2503: Cannot find namespace 'alias'.
        at org.junit.Assert.fail(Assert.java:88)
        at com.google.javascript.clutz.DeclarationSyntaxTest.runChecked(DeclarationSyntaxTest.java:171)
        at com.google.javascript.clutz.DeclarationSyntaxTest.doTestDeclarationUsage(DeclarationSyntaxTest.java:160)
        at com.google.javascript.clutz.DeclarationSyntaxTest.testDeclarationUsage(DeclarationSyntaxTest.java:142)
```

And four failures in the gents tests - all of which appear to be related to whitespace in the output typescript for type unions in the return of functions - the best example is the first failure :

```
com.google.javascript.gents.TypeScriptGeneratorTests > functions.js FAILED
    expected:<...ing, x: any): string[ | ]null {
      if (b) {
      ...> but was:<...ing, x: any): string[|]null {
      if (b) {
      ...>
```

I don't need the clutz command - but I would like to use gents.

I could fix the gents failures by changing the golden file - but I (personally) prefer the whitespace. What's the intended behaviour here?

I've looked but haven't found an identifiable place where the return type for a function is generated/written out. Can anyone give me some guidance? This smells like something fairly straightforward to fix?

**Comment by awk** [comment]
Debugging though the test the problem appears to be that the clang format pass (tryClangFormat) at the end of `generateTypescript` is stripping the whitespace from the type union on my machine.

This looks to be because clang-format 1.2.2 (which I got as being 'compatible' with ^1.0.48) has this behaviour. If I pin the clang-format rpm-module to 1.0.48 the gents tests pass (the clutz test still fails though).

**Comment by rkirov** [comment]
Good find! Do you know why the shrinkwrap didn't pin to 1.0.48 (I thought that's the whole point of it)

https://github.com/angular/clutz/blob/master/npm-shrinkwrap.json#L30

**Comment by awk** [comment]
Aaahhh! I hadn't noticed the shrinkwrap ! It was probably not pinned correctly for me because I use `yarn` to install the dependencies (and there's no checked in yarn.lock :-)

**Comment by rkirov** [comment]
Also I got to the bottom of the mysterious 'reserved_var_names.d.ts' errors, see ehttps://github.com/angular/clutz/issues/594#issuecomment-387573566. Sounds like there is nothing else actionable left on this issue.
