### ISSUE TITLE
Incremental Clutz breaks static/instance split

### ISSUE THREAD

**Issue by LucasSloan** [angular/clutz#713]
In closure, classes don't inherit the static properties of classes they extend.  To model this, we declare classes in two parts, one with all static properties and one with all instance properties, and have all the inheritance work on the instance side:

```typescript
  class Parent extends Parent_Instance {
  }
  class Parent_Instance {
  }
  class Child extends Child_Instance {
  }
  class Child_Instance extends Parent_Instance {
  }
```

In moving to incremental clutz, we broke this by having the child instance class extend the parent static class:

```typescript
  class Parent extends Parent_Instance {
  }
  class Parent_Instance {
  }
  class Child extends Child_Instance {
  }
  class Child_Instance extends Parent {
  }
```

This causes a large number of implicit anys in our typings.  Reverting to the old behavior is easy, but interacts poorly with declareLegacyNamespace(), where we only expose the static side, not the instance side.  I'll do a little poking to see how easy that is to fix.

**Comment by rkirov** [comment]
Fixed with - https://github.com/angular/clutz/commit/0e66d9da1f49c0573140b3847de84493aa08baa4
