### ISSUE TITLE
CustomEvent changed in TS2.7

### ISSUE THREAD

**Issue by evmar** [angular/clutz#725]
2.6:
interface CustomEvent extends Event {

2.7:
interface CustomEvent<T = any> extends Event {

So TS code generates references to CustomEvent<X> which is illegal in Closure JS.
I think the fix is for Clutz to define CustomEvent that matches the TS one and translate it to the Closure one.

**Comment by mprobst** [comment]
You mean with tsickle_typed we produce CustomEvent (no generic type arg),
and that then breaks in Closure?

>
That actually sounds to me like tsickle needs to handle default generic
type arguments and emit them for Closure's sake.

**Comment by evmar** [comment]
It's the reverse -- in 2.7 we generate references to CustomEvent<T>, while the Closure one is bare CustomEvent.

But I think you're right, this should be in tsickle.

**Comment by evmar** [comment]
I'm going to solve this instead by making the Closure type match this.
