### ISSUE TITLE
gents does not remove @tempalte in comments

### ISSUE THREAD

**Issue by jplaisted** [angular/clutz#793]
```
/**
 * @param {T} t
 * @return {T} 
 * @template T
 */
function pass(t) { return t; }
```

```
/**
 * @template T
 */
function pass(t: T): T {
  return t;
}
```

The `@template T` comment sticks around.

**Comment by rkirov** [comment]
Added basic support for classes - https://github.com/angular/clutz/commit/5b4ec54f298993bfd43e59daf05ee5ab655cd297

Still in work adding support for functions/methods.

**Comment by rkirov** [comment]
Fixed with https://github.com/angular/clutz/commit/e2087d64e2bdb5c44d649014f274de5ebadc8740
