### ISSUE TITLE
gents whitespace regression

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#824]
Currently, gents is broken at head due to new removal of whitespace in almost all golden files. Likely this is due to the an underlying Closure change.

As a first order of business, we should fix the build and then investigate how to get back the proper whitespace.

**Comment by teppeis** [comment]
@rkirov Test results of snapshots:

- Pass: `com.google.javascript:closure-compiler:1.0-20190107.193122-442`
- Fail: `com.google.javascript:closure-compiler:1.0-20190108.212204-443`

This commit? https://github.com/google/closure-compiler/commit/fdd9b92d01865eaaac85bf6d01b0659a0a624c58

**Comment by rkirov** [comment]
Yep, it's definitely that. Not clear if we can fix forward on our side. @bowenni and I will look through the whitespace reinsertion hack we do in gents and see if we can recover the old behavior. Let us know if you have any insights into this too.
