### ISSUE TITLE
[gents] arrow functions with a single argument are not emitted properly syntactically

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#853]
A recent change in closure, seems to have stated stripping off the parens around arrow functions with a single argument - `(x) => {...}` turns to `x => { ... }` during pretty printing.

However, when we inject a type that wasn't there already this is no longer syntactically valid `x : string => {...}`. The test is turned off to make the build red again, but this issue tracks a proper fix of it (and re-enabling the test).

**Comment by mprobst** [comment]
I think there's a fix in google3 for this, you need to set the output
language to es2016 typed.
