### ISSUE TITLE
Closure's `goog.isDefAndNotNull` seem to affect type inference and make clutz emit extra 'any's

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#888]
Minimal repro is:

```js
/**
 * @param {?some.C} c
 */
is.def.and.not.null = function (c) {
  //!! isDefAndNotNull seems to affect the inferencer to start reporting
  //!! some.C as the ? type in compiler.getTopScope().getAllSymbols().
  //!! I am not sure why that happens, or how to fix it, so for now this
  //!! test is solely tracking this odd behavior.
  if (!goog.isDefAndNotNull(some.C)) {
    return c;
  }
};
```

Clutz's extra processUnprovidedTypes pass now emits:

```js
declare namespace ಠ_ಠ.clutz.some {
  let C : any ;
}
```

This is problematic because it might win over the proper clutz emit for `some.C` and now `C` cannot be used as a type.

**Comment by concavelenz** [comment]
Would "some" here be an unresolved type?

**Comment by rkirov** [comment]
https://github.com/angular/clutz/pull/889/files#diff-4ccee7896ec5ef2b3f0885562e4f1be2 is the full e2e repro. Indeed `some.C` is a type that is unresolved in clutz's --assumeForwardDeclare run.

**Comment by rkirov** [comment]
`goog.isDefAndNotNull` is going to be removed, which seems to fix this issue.
